package com.example.be.exception;

public enum ErrorCode {
    BAD_REQUEST,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CREDENTIALS,
    VALIDATION_FAILED,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_SERVER_ERROR,

    USER_EMAIL_ALREADY_REGISTERED,
    USER_PHONE_ALREADY_REGISTERED,
    CURRENT_USER_NOT_FOUND,
    CURRENT_PASSWORD_INCORRECT,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_SUBJECT_NOT_FOUND,
    STAFF_PASSWORD_REQUIRED,

    CATEGORY_NAME_REQUIRED,
    CATEGORY_NAME_ALREADY_EXISTS,
    PRODUCT_CODE_REQUIRED,
    PRODUCT_CODE_ALREADY_EXISTS,
    PRODUCT_GENDER_INVALID,
    PRODUCT_VARIANT_DUPLICATE,
    CART_QUANTITY_INVALID,

    ORDER_STATUS_REQUIRED,
    ORDER_STATUS_TRANSITION_INVALID,
    ORDER_OWNERSHIP_MISMATCH,
    ORDER_CANCELLATION_REASON_REQUIRED,
    ORDER_ALREADY_CANCELLED,
    ORDER_CANCELLATION_NOT_ALLOWED,
    ORDER_CANCELLATION_IN_DELIVERY_NOT_ALLOWED,
    ORDER_CANCEL_REQUEST_NOT_PENDING,
    ORDER_RETURN_NOT_ALLOWED,
    ORDER_CONFIRMATION_NOT_ALLOWED,
    ORDER_ITEM_PRODUCT_MISSING,
    ORDER_ITEM_QUANTITY_INVALID,
    STAFF_FALLBACK_NOT_AVAILABLE,

    REVIEW_ALREADY_SUBMITTED,
    REVIEW_NOT_OWN_ORDER,
    REVIEW_STATUS_NOT_ALLOWED,
    REVIEW_PRODUCT_NOT_IN_ORDER,
    REVIEW_IMAGE_LIMIT_EXCEEDED,
    REVIEW_IMAGE_INVALID_FORMAT,

    STOCK_INSUFFICIENT,
    PRODUCT_VARIANT_NOT_FOUND,
    MONEY_INVALID_AMOUNT,
    MONEY_DISCOUNT_EXCEEDS_SUBTOTAL,
    
    // Supplier (Nhà cung cấp) errors
    SUPPLIER_NOT_FOUND,
    SUPPLIER_CODE_ALREADY_EXISTS,
    SUPPLIER_NAME_PHONE_ALREADY_EXISTS,
    SUPPLIER_EMAIL_ALREADY_EXISTS,
    SUPPLIER_HAS_RELATED_DATA,
    SUPPLIER_PHONE_INVALID,
    SUPPLIER_EMAIL_INVALID
}
